name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "40 6 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ce6acd4e1c171fb09fd89f659efe227e
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
